--liquibase formatted sql

--changeset author:1
CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    status INT
);

CREATE TABLE payment_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number VARCHAR(50) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    card_type VARCHAR(20) NOT NULL,
    client_id BIGINT NOT NULL,
    CONSTRAINT uq_card_number UNIQUE (card_number),
    CONSTRAINT fk_card_client FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE
);
