spring.application.name=bank-test-task

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bank_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:mySuperSecureSecretKeyForBankApp2026MustBeAtLeast32CharsLong}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Default User Credentials
app.security.username=${SECURITY_USERNAME:admin}
app.security.password=${SECURITY_PASSWORD:admin}